name: Sync to Iresh-udayanga

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push to Iresh-udayanga
        run: |
          git push --prune --force https://Iresh-udayanga:${{ secrets.SYNC_PAT }}@github.com/Iresh-udayanga/topjobs-scraper.git main:main